sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3

gemfile:
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_50.gemfile
  - gemfiles/active_record_51.gemfile
  - gemfiles/active_record_52.gemfile
  - gemfiles/active_record_60.gemfile

matrix:
  exclude:
    - rvm: 2.2.10
      gemfile: gemfiles/active_record_master.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/active_record_master.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/active_record_60.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/active_record_60.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/active_record_60.gemfile

before_install: gem install bundler
