sudo: false
language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1

gemfile:
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_50.gemfile
  - gemfiles/active_record_51.gemfile
  - gemfiles/active_record_52.gemfile
  - gemfiles/active_record_master.gemfile

before_install: gem install bundler
