sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.2

gemfile:
  - gemfiles/active_record_42.gemfile
  - gemfiles/active_record_50.gemfile
  - gemfiles/active_record_51.gemfile
  - gemfiles/active_record_master.gemfile

before_install: gem install bundler -v 1.12.5
